FROM nvidia/cuda:7.5-cudnn5-devel
MAINTAINER Ly Nguyen <lynguyen@amazon.com>

#Install dependencies
RUN apt-get update
RUN sudo apt-get install -y build-essential
RUN sudo apt-get install -y cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
RUN sudo apt-get install -y python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev

# OPENCV
#RUN apt-get install -y libopencv-dev
RUN git clone https://github.com/Itseez/opencv.git
RUN cd opencv
RUN mkdir release
RUN cd release
RUN cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local ..
RUN make -j8
RUN sudo make install
RUN cd ../..

# BLAS
RUN apt-get install -y libatlas-base-dev

# PYTHON2
RUN apt-get install -y python-setuptools python-pip python-dev unzip gfortran
RUN pip install numpy nose scipy

# PYTHON3
RUN apt-get install -y python3-setuptools python3-pip
RUN pip3 install numpy nose scipy && ln -s -f /usr/local/bin/nosetests-3.4 /usr/local/bin/nosetests3

# TESTDEPS
RUN apt-get install -y libgtest-dev cmake wget
RUN cd /usr/src/gtest && cmake CMakeLists.txt && make && cp *.a /usr/lib
RUN pip install nose cpplint 'pylint==1.4.4' 'astroid==1.3.6'

# MAVEN
RUN apt-get install -y maven default-jdk

#NOTEBOOK
RUN apt-get -y install ipython ipython-notebook
RUN python -m pip install -U pip
RUN pip install jupyter
RUN apt-get -y install graphviz
RUN pip install graphviz
RUN pip install opencv-python
RUN apt-get -y install git
RUN pip install --upgrade setuptools
RUN pip install matplotlib
RUN pip install sklearn