# For tutorial testing
FROM mxnet/ubuntu:latest

RUN apt-get update
RUN apt-get -y install git
RUN apt-get -y install python-opencv
RUN apt-get -y install ipython ipython-notebook
RUN apt-get -y install graphviz
RUN wget -qO- https://get.docker.com/ | sh
RUN usermod -aG docker $(whoami)
RUN python -m pip install -U pip
RUN pip install virtualenv
