# For tutorial testing
FROM mxnet/ubuntu:latest

RUN apt-get update
RUN apt-get -y install git
RUN apt-get -y install python-opencv
RUN apt-get -y install ipython ipython-notebook
RUN apt-get -y install graphviz
RUN apt-get -y install doxygen
RUN apt-get -y install scala
RUN python -m pip install -U pip
RUN pip install virtualenv
RUN pip install sphinx==1.5.1 CommonMark==0.5.4 breathe mock==1.0.1 recommonmark pypandoc
RUN pip install --upgrade requests