# For tutorial testing
FROM mxnet/ubuntu:latest

COPY install/ubuntu_*.sh /install/
RUN /install/ubuntu_install_scala.sh
RUN wget http://downloads.lightbend.com/scala/2.11.8/scala-2.11.8.deb && \
    dpkg -i scala-2.11.8.deb && rm scala-2.11.8.deb

RUN apt-get update
RUN apt-get -y install git
RUN apt-get -y install python-opencv
RUN apt-get -y install ipython ipython-notebook
RUN apt-get -y install graphviz
RUN apt-get -y install doxygen
RUN apt-get -y install pandoc

RUN python -m pip install -U pip
RUN pip install virtualenv
RUN pip install sphinx==1.5.1 CommonMark==0.5.4 breathe mock==1.0.1 recommonmark pypandoc
RUN pip install --upgrade requests